apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-process-redis
spec:
  selector:
    matchLabels:
      app: data-process-redis
  replicas: 1
  template:
    metadata:
      labels:
        app: data-process-redis
    spec:
      containers:
      - name: data-process-redis
        image: clearlifezhang/my-data-process-redis-service:latest
        ports:
        - containerPort: 6060
        env:
        - name: REDIS_SERVER_HOST
          value: redis-server
        - name: REDIS_SERVER_PORT
          value: "6379"
---
apiVersion: v1
kind: Service
metadata:
  name: data-process-redis
spec:
  selector:
    app: data-process-redis
  type: NodePort
  ports:
    - protocol: TCP
      port: 6060
      targetPort: 6060
      nodePort: 30660

